package com.complaintiq.notification.enums;
public enum NotificationType {
    COMPLAINT_RECEIVED, COMPLAINT_ASSIGNED, SLA_WARNING, SLA_BREACHED,
    COMPLAINT_RESOLVED, COMPLAINT_ESCALATED, FEEDBACK_REQUEST, COMPLAINT_REOPENED
}
